### PR TITLE
added enrichment to remove a property from the mapped document.

### PR DESCRIPTION
**Pull request by mdellabitta**

### CODE REVIEW

**Comment by mdellabitta** [comment]
Decided to make this generic rather than hardcoding `sourceResource/collection`.

**Comment by AudreyAltman** [comment]
@mdellabitta what do you want to do about the codacy complaint?

**Comment by mdellabitta** [comment]
@AudreyAltman looks like Codacy likes that more. If you're OK with it, could you squash and merge?

**Comment by AudreyAltman** [comment]
Squashed.  Will merge when tests pass.

**Pull request merged**
