### PR TITLE
Improve BHL mapping based on feedback

### PR DESCRIPTION
**Pull request by markbreedlove**
See https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1191

This should take care of the issues in that ticket.

I'm also adding unit tests. (Imagine that!)

### CODE REVIEW

**Comment by markbreedlove** [comment]
I'll re-run the mapping / enrichments in our QA environment after an initial review, but we should hold off on merging until it's gone through that additional reenrichment.

**Comment by markbreedlove** [comment]
Sorry to move things out from under you if you're reviewing this, but I've made some fixes and test improvements.

**Comment by markbreedlove** [comment]
Thanks, @moltude! I've updated the comment.

**Comment by markbreedlove** [comment]
Reviewers, I'm re-ingesting this into our QA environment.

**Comment by markbreedlove** [comment]
Ah, I missed something.  I'm stripping "\" (backslash) characters from the title, instead of "/" (forward slash). I'll commit a change to fix this.  (take note, @guegueng)

**Comment by guegueng** [comment]
@mb, I'm also realizing that we should remove "." from the ends of the titles as well. I am going to update the ticket as well, but while you are at it, thought I'd let you know

**Comment by markbreedlove** [comment]
Oh, OK. I thought that it was legitimate to preserve the period because it's the old-fashioned representation of a title. E.g. the magazine "The Nation" still uses "The Nation."

**Comment by guegueng** [comment]
I think our punctuation enrichment removes periods at the ends of sentences anyway. In this case, with the addition of the other title parts, it looks especially bad.

**Comment by markbreedlove** [comment]
For the historical record, see also https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1210. This followup story called for further revisions to the mapping, including reintroducing a `collection` mapping that was removed for the earlier story.

**Comment by markbreedlove** [comment]
I have squashed and rebased.

I elected to keep 18 commits rather than squashing them down to a smaller number, since I'm modifying existing files, and keeping a commit for roughly each thing that had to be changed should make it easier to diagnose issues with individual functions. I did squash various fixups and related additions, though.

**Comment by moltude** [comment]
👍

**Pull request merged**
