### PR TITLE
Rewrite Internet Archive fetcher

### PR DESCRIPTION
**Pull request by markbreedlove**
See https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1391

This changeset rewrites the Internet Archive fetcher to use IA's `internetarchive` Python module.

A new test suite has been dedicated to the Internet Archive harvester.

You probably want to click "view" on the `ia_fetcher.py` diff and just read the new file.

### CODE REVIEW

**Comment by markbreedlove** [comment]
Sorry to do this, but you may want to hold off on reviewing this. I've found an issue and need to update a test and fix something in the harvester.

**Comment by AudreyAltman** [comment]
No problem - just let me know when you're ready for me to review.

**Comment by markbreedlove** [comment]
OK, @AudreyAltman, it's fixed.

**Comment by markbreedlove** [comment]
Codacy caught a couple of things that I can change quickly ...

**Comment by AudreyAltman** [comment]
This looks good to me.  Do you want to squash your commits?

**Comment by markbreedlove** [comment]
That's OK, I'll squash them ...

**Pull request merged**
